### In this notebook I will:
1. Pull the clean filtered data from arrests (that has removed duplicates and blank identifiers)
2. Use the unique identifiers there to cut through the raw parquet data of detentions
3. Join the clean filtered arrests data and the new filtered detentions data on the unique identifier data

In [1]:
import pandas as pd

In [2]:
pip install pyarrow

Requirement already satisfied: pyarrow in /Users/sajinashrestha/opt/anaconda3/lib/python3.9/site-packages (21.0.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
##pulling in the data we got into this notebook
df = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/FilteredData/2025NYArrests_070626.csv', low_memory=False)
df

,apprehension_date,apprehension_aor,final_program,apprehension_method,apprehension_criminality,case_status,case_category,departure_country,final_order_yes_no,age,...,apprehension_site_landmark,toa_current_duty_site,case_criminality,case_threat_level,unique_identifier,apprehension_date_time,duplicate_likely,file_original,sheet_original,row_original
0,1/2/2025,Buffalo Area of Responsibility,ERO Criminal Alien Program,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,HONDURAS,YES,34,...,FEDERAL CORRECTIONAL INSTITUTE RAY BROOK,"ERO - Champlain, NY Sub-Office",1 Convicted Criminal,1.0,baedf81fae1fd75a5f311ad042c51575fe127f35,2025-01-02 09:00:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,169580
1,1/2/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8C] Excludable / Inadmissible - Administrativ...,NaN,YES,19,...,"NDD - 26 FEDERAL PLAZA NY, NY","NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,254cce2f2a6ae9d741b12989c5501a0ff2c6b3ca,2025-01-02 09:32:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,33838
2,1/2/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,MEXICO,YES,37,...,"NDD - 26 FEDERAL PLAZA NY, NY","NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,38b5ed10cf4cdb766b508bf9f09f79399c96d0ff,2025-01-02 09:39:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,51499
3,1/2/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,MEXICO,YES,8,...,"NDD - 26 FEDERAL PLAZA NY, NY","NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,873861a4a6aa526918a4548de378a9cc23d6220f,2025-01-02 10:00:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,122696
4,1/2/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,MEXICO,YES,6,...,"NDD - 26 FEDERAL PLAZA NY, NY","NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,a29f48cac1afb7324eb7f0ae26d5f27576a5cd56,2025-01-02 10:10:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,147470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10769,12/31/2025,New York City Area of Responsibility,Fugitive Operations,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,GUATEMALA,YES,30,...,FUGITIVE OPERATIONS NY STATE,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,bb9ecc5b3c48ea3392b39b335359417cc96756f2,2025-12-31 15:35:57+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,134863
10770,12/31/2025,Buffalo Area of Responsibility,Fugitive Operations,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,29,...,MONROE COUNTY,BATAVIA CMD CTR NY DCO,3 Other Immigration Violator,NaN,f3825b86ca6954770e3af431dd812083330e33e0,2025-12-31 16:16:15+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,175277
10771,12/31/2025,New York City Area of Responsibility,Alternatives to Detention,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,ECUADOR,YES,36,...,"CIP GENERAL AREA, NON-SPECIFIC","ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NaN,e64f9b0e481ff3ba2f2970c4fad2c6870563a28b,2025-12-31 22:30:00+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,165653
10772,12/31/2025,New York City Area of Responsibility,Alternatives to Detention,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,PERU,YES,35,...,"CIP GENERAL AREA, NON-SPECIFIC","ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NaN,dd9306e1321f7485dddc8e2b2cf21bac052dd7b6,2025-12-31 22:45:04+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,159286
10773,12/31/2025,New York City Area of Responsibility,Alternatives to Detention,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,PERU,YES,10,...,"CIP GENERAL AREA, NON-SPECIFIC","ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NaN,ac68b01985954d30ce19b8887e2f3e13e5e02be0,2025-12-31 23:05:25+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,123892

In [4]:
df_UI = df['unique_identifier']
df_UI

0        baedf81fae1fd75a5f311ad042c51575fe127f35
1        254cce2f2a6ae9d741b12989c5501a0ff2c6b3ca
2        38b5ed10cf4cdb766b508bf9f09f79399c96d0ff
3        873861a4a6aa526918a4548de378a9cc23d6220f
4        a29f48cac1afb7324eb7f0ae26d5f27576a5cd56
                           ...
10769    bb9ecc5b3c48ea3392b39b335359417cc96756f2
10770    f3825b86ca6954770e3af431dd812083330e33e0
10771    e64f9b0e481ff3ba2f2970c4fad2c6870563a28b
10772    dd9306e1321f7485dddc8e2b2cf21bac052dd7b6
10773    ac68b01985954d30ce19b8887e2f3e13e5e02be0
Name: unique_identifier, Length: 10774, dtype: object

In [9]:
df_UI2 = df_UI.to_frame()
df_UI2

                              unique_identifier
0      baedf81fae1fd75a5f311ad042c51575fe127f35
1      254cce2f2a6ae9d741b12989c5501a0ff2c6b3ca
2      38b5ed10cf4cdb766b508bf9f09f79399c96d0ff
3      873861a4a6aa526918a4548de378a9cc23d6220f
4      a29f48cac1afb7324eb7f0ae26d5f27576a5cd56
...                                         ...
10769  bb9ecc5b3c48ea3392b39b335359417cc96756f2
10770  f3825b86ca6954770e3af431dd812083330e33e0
10771  e64f9b0e481ff3ba2f2970c4fad2c6870563a28b
10772  dd9306e1321f7485dddc8e2b2cf21bac052dd7b6
10773  ac68b01985954d30ce19b8887e2f3e13e5e02be0

[10774 rows x 1 columns]

In [5]:
df_RAWDetentions = pd.read_parquet('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/detention-stays-latest.parquet')
df_RAWDetentions

,stay_ID,n_stints,detention_facility_codes_all,unique_identifier,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,stay_release_reason,religion,gender,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
0,33342b2832acf82179e0df53a43d957099d262e4_2004-...,2,JCRLYTX; JCRLYTX,33342b2832acf82179e0df53a43d957099d262e4,2004-12-05 22:30:00+00:00,2025-01-23 22:30:00+00:00,2025-01-23,Removed,None,Male,...,2025-01-23 22:30:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Conroe,TX,Montgomery
1,de10c6a3d0027b9a7bf15e7ae0726e67f733bd81_2011-...,4,YORCOPA; MIAHOLD; FLDSSFS; KRO,de10c6a3d0027b9a7bf15e7ae0726e67f733bd81,2011-01-11 23:59:00+00:00,NaT,None,None,None,Male,...,NaT,York,PA,York,York,PA,York,Miami,FL,Miami-Dade
2,ad00adabb36933a9ae532721b36b572b7a70b09f_2011-...,2,ECC; PIC,ad00adabb36933a9ae532721b36b572b7a70b09f,2011-05-11 13:00:35+00:00,2026-02-10 02:58:00+00:00,2026-02-10,Removed,None,Male,...,2026-02-10 02:58:00+00:00,El Centro,CA,Imperial,El Centro,CA,Imperial,Los Fresnos,TX,Cameron
3,20acf28b12065c2144c5106fab1698f79c43a7a2_2012-...,3,HOUHOLD; MTGHOLD; MTGPCTX,20acf28b12065c2144c5106fab1698f79c43a7a2,2012-11-06 09:43:00+00:00,2026-01-27 12:00:00+00:00,2026-01-27,Removed,None,Male,...,2026-01-27 12:00:00+00:00,Houston,TX,Harris,Houston,TX,Harris,Conroe,TX,Montgomery
4,367c0c726a1428444b6aefdbd0f6a2b877ad0f2f_2014-...,2,FREHOLD; LOSHOLD,367c0c726a1428444b6aefdbd0f6a2b877ad0f2f,2014-01-17 13:18:00+00:00,2025-02-08 05:28:00+00:00,2025-02-08,Removed,None,Male,...,2025-02-08 05:28:00+00:00,None,CA,None,None,CA,None,Los Angeles,CA,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087412,6cece9f08499216f65ba3be7200e5bdb6b7add7e_2026-...,1,SJS,6cece9f08499216f65ba3be7200e5bdb6b7add7e,2026-03-10 23:40:00+00:00,NaT,None,None,None,Male,...,NaT,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo
1087413,a9792bfd2c9dc036a74e802047f3f9ee958892c1_2026-...,1,DHDFNJ,a9792bfd2c9dc036a74e802047f3f9ee958892c1,2026-03-10 23:47:00+00:00,NaT,None,None,None,Male,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087414,1dd7bb2de9c3e8fc58962a25db518715b3cef54e_2026-...,1,DHDFNJ,1dd7bb2de9c3e8fc58962a25db518715b3cef54e,2026-03-10 23:57:00+00:00,NaT,None,None,None,Male,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087415,011a0c9d77115c9902c6b4f20667f2e2b75c85cb_2026-...,1,PLYMOMA,011a0c9d77115c9902c6b4f20667f2e2b75c85cb,2026-03-11 00:13:00+00:00,NaT,None,None,None,Male,...,NaT,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth
1087416,5a72db4bb17f84699ff794292f9dd0f5d86f12d9_2026-...,1,ELZICDF,5a72db4bb17f84699ff794292f9dd0f5d86f12d9,2026-03-11 00:30:00+00:00,NaT,None,None,None,Male,...,NaT,Elizabeth,NJ,Union,Elizabeth,NJ,Union,Elizabeth,NJ,Union

In [10]:
##now wwe ask the notebook to use these unique identifiers to pull only those from the detentions list

filtered_detentions = df_RAWDetentions[df_RAWDetentions['unique_identifier'].isin(df_UI2['unique_identifier'])]
filtered_detentions

,stay_ID,n_stints,detention_facility_codes_all,unique_identifier,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,stay_release_reason,religion,gender,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
31,56ee25358945f67089e40922608ff2b1a1396a72_2018-...,1,CCASDCA,56ee25358945f67089e40922608ff2b1a1396a72,2018-12-31 17:32:00+00:00,2023-02-08 18:11:00+00:00,2023-02-08,Removed,None,Male,...,2023-02-08 18:11:00+00:00,San Diego,CA,San Diego,San Diego,CA,San Diego,San Diego,CA,San Diego
40,4e448daffa72171ce7670fe9aa17f98050fbe35c_2019-...,1,BTV,4e448daffa72171ce7670fe9aa17f98050fbe35c,2019-03-28 09:22:00+00:00,2024-04-05 15:00:00+00:00,2024-04-05,Order of recognizance,None,Male,...,2024-04-05 15:00:00+00:00,Batavia,NY,Genesee,Batavia,NY,Genesee,Batavia,NY,Genesee
226,2782c92f42cfa9b8dd7640b1de29652cce2ea682_2021-...,2,JENADLA; JENATLA,2782c92f42cfa9b8dd7640b1de29652cce2ea682,2021-02-26 13:10:00+00:00,2022-10-11 10:02:00+00:00,2022-10-11,Removed,None,Male,...,2022-10-11 10:02:00+00:00,Jena,LA,LaSalle,Jena,LA,LaSalle,Alexandria,LA,Rapides
267,5fd376c3b771aed2d9c5062f1eff801c2eacde07_2021-...,2,BOONEKY; LOUHOLD,5fd376c3b771aed2d9c5062f1eff801c2eacde07,2021-05-18 13:57:00+00:00,2022-12-16 12:54:00+00:00,2022-12-16,Order of Supervision - No SLRRFF,None,Male,...,2022-12-16 12:54:00+00:00,Burlington,KY,Boone,Burlington,KY,Boone,None,KY,None
1210,c1ca2efd571727208d4ca420bd905b998257b22b_2022-...,2,FIPCAGA; STWRTGA,c1ca2efd571727208d4ca420bd905b998257b22b,2022-03-18 08:10:00+00:00,2023-01-21 08:38:00+00:00,2023-01-21,Order of supervision,None,Male,...,2023-01-21 08:38:00+00:00,Folkston,GA,Charlton,Folkston,GA,Charlton,Lumpkin,GA,Stewart
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075482,dc5fc5f142cd5389ec60fe7f9706d67660fac357_2026-...,1,IRADFCA,dc5fc5f142cd5389ec60fe7f9706d67660fac357,2026-02-27 09:00:00+00:00,NaT,None,None,None,Male,...,NaT,Calexico,CA,Imperial,Calexico,CA,Imperial,Calexico,CA,Imperial
1080650,1a4039c889e5cc4ca85935e4ed449d5968455202_2026-...,3,MADISNY; SYRHOLD; BTV,1a4039c889e5cc4ca85935e4ed449d5968455202,2026-03-04 10:01:00+00:00,NaT,None,None,None,Male,...,NaT,Wampsville,NY,Madison,Batavia,NY,Genesee,Batavia,NY,Genesee
1082764,ed2daa1af058ed646b8009f6ae3d06a7ea592232_2026-...,2,NYCHOLD; ORANGNY,ed2daa1af058ed646b8009f6ae3d06a7ea592232,2026-03-05 21:22:00+00:00,2026-03-09 09:48:00+00:00,2026-03-09,U.S. Marshals or other agency (explain in Dete...,None,Male,...,2026-03-09 09:48:00+00:00,New York,NY,New York,Goshen,NY,Orange,Goshen,NY,Orange
1085696,f4972aa253091956922a5db8ac6dbae3dd62fbb3_2026-...,1,NYCHOLD,f4972aa253091956922a5db8ac6dbae3dd62fbb3,2026-03-09 12:28:00+00:00,2026-03-10 18:15:00+00:00,2026-03-10,Transferred,None,Male,...,2026-03-10 18:15:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
1086849,85021aab1d8e0c5705721e610ecae6241ad259e6_2026-...,2,NYCHOLD; ORANGNY,85021aab1d8e0c5705721e610ecae6241ad259e6,2026-03-10 12:22:00+00:00,NaT,None,None,None,Male,...,NaT,New York,NY,New York,New York,NY,New York,Goshen,NY,Orange

In [13]:
##merge the two dataframes on unique identifier
ArrestsDetentions = pd.merge(df, filtered_detentions, on="unique_identifier")
ArrestsDetentions

,apprehension_date,apprehension_aor,final_program_x,apprehension_method,apprehension_criminality,case_status_x,case_category_x,departure_country_x,final_order_yes_no_x,age,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
0,1/2/2025,Buffalo Area of Responsibility,ERO Criminal Alien Program,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,HONDURAS,YES,34,...,2025-02-21 06:24:00+00:00,Plattsburgh,NY,Clinton,Batavia,NY,Genesee,Alexandria,LA,Rapides
1,1/2/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8C] Excludable / Inadmissible - Administrativ...,NaN,YES,19,...,2025-01-02 13:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
2,1/2/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,MEXICO,YES,37,...,2025-01-02 13:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
3,1/2/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,MEXICO,YES,37,...,2025-11-28 07:34:00+00:00,New York,NY,New York,Dilley,TX,Frio,Dilley,TX,Frio
4,11/15/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,MEXICO,YES,37,...,2025-01-02 13:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11819,12/31/2025,New York City Area of Responsibility,Fugitive Operations,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,NaN,NaN,NO,33,...,NaT,New York,NY,New York,Folkston,GA,Charlton,Folkston,GA,Charlton
11820,12/31/2025,New York City Area of Responsibility,Fugitive Operations,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,GUATEMALA,YES,30,...,2026-01-12 09:09:00+00:00,New York,NY,New York,Natchez,MS,Adams,Natchez,MS,Adams
11821,12/31/2025,Buffalo Area of Responsibility,Fugitive Operations,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,29,...,NaT,Batavia,NY,Genesee,Batavia,NY,Genesee,Batavia,NY,Genesee
11822,12/31/2025,New York City Area of Responsibility,Alternatives to Detention,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,PERU,YES,35,...,2023-03-30 15:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
11823,12/31/2025,New York City Area of Responsibility,Alternatives to Detention,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,PERU,YES,10,...,2023-03-30 19:32:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York

In [14]:
ArrestsDetentions['unique_identifier'].value_counts()

049184c63b97ee0c2d5bf8691383ee3506d444cb    6
f0e2572ff5faaefb6497747f10f7c7970d45c878    6
d702cd683a232a40680986ad44edc7744990d8bb    6
dfaa53a67218bfa4cfd2c8e93fbb8238ab44378f    6
3d84311c9a0df42fc5270f3a470c57ec4475d211    6
                                           ..
a0a0601bce4878c31a863178800482a6e25b5b5f    1
fee5720b89ef9f3f752ee48fe3fb53708e6afc06    1
20e702bffb316d4ff13a7b3bf841baa0c61b776c    1
e4ef4187099c6c4ef5028bc6f24594fb4e6a8ace    1
ac68b01985954d30ce19b8887e2f3e13e5e02be0    1
Name: unique_identifier, Length: 10453, dtype: int64

In [15]:
ArrestsDetentions.to_csv('Filtereddata/2025ArrestsDetentions_070726.csv', index = False)