In [1]:
import pandas as pd

In [2]:
pip install pyarrow

Requirement already satisfied: pyarrow in /Users/sajinashrestha/opt/anaconda3/lib/python3.9/site-packages (21.0.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
df = pd.read_parquet('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/detention-stays-latest.parquet')
df

,stay_ID,n_stints,detention_facility_codes_all,unique_identifier,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,stay_release_reason,religion,gender,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
0,33342b2832acf82179e0df53a43d957099d262e4_2004-...,2,JCRLYTX; JCRLYTX,33342b2832acf82179e0df53a43d957099d262e4,2004-12-05 22:30:00+00:00,2025-01-23 22:30:00+00:00,2025-01-23,Removed,None,Male,...,2025-01-23 22:30:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Conroe,TX,Montgomery
1,de10c6a3d0027b9a7bf15e7ae0726e67f733bd81_2011-...,4,YORCOPA; MIAHOLD; FLDSSFS; KRO,de10c6a3d0027b9a7bf15e7ae0726e67f733bd81,2011-01-11 23:59:00+00:00,NaT,None,None,None,Male,...,NaT,York,PA,York,York,PA,York,Miami,FL,Miami-Dade
2,ad00adabb36933a9ae532721b36b572b7a70b09f_2011-...,2,ECC; PIC,ad00adabb36933a9ae532721b36b572b7a70b09f,2011-05-11 13:00:35+00:00,2026-02-10 02:58:00+00:00,2026-02-10,Removed,None,Male,...,2026-02-10 02:58:00+00:00,El Centro,CA,Imperial,El Centro,CA,Imperial,Los Fresnos,TX,Cameron
3,20acf28b12065c2144c5106fab1698f79c43a7a2_2012-...,3,HOUHOLD; MTGHOLD; MTGPCTX,20acf28b12065c2144c5106fab1698f79c43a7a2,2012-11-06 09:43:00+00:00,2026-01-27 12:00:00+00:00,2026-01-27,Removed,None,Male,...,2026-01-27 12:00:00+00:00,Houston,TX,Harris,Houston,TX,Harris,Conroe,TX,Montgomery
4,367c0c726a1428444b6aefdbd0f6a2b877ad0f2f_2014-...,2,FREHOLD; LOSHOLD,367c0c726a1428444b6aefdbd0f6a2b877ad0f2f,2014-01-17 13:18:00+00:00,2025-02-08 05:28:00+00:00,2025-02-08,Removed,None,Male,...,2025-02-08 05:28:00+00:00,None,CA,None,None,CA,None,Los Angeles,CA,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087412,6cece9f08499216f65ba3be7200e5bdb6b7add7e_2026-...,1,SJS,6cece9f08499216f65ba3be7200e5bdb6b7add7e,2026-03-10 23:40:00+00:00,NaT,None,None,None,Male,...,NaT,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo
1087413,a9792bfd2c9dc036a74e802047f3f9ee958892c1_2026-...,1,DHDFNJ,a9792bfd2c9dc036a74e802047f3f9ee958892c1,2026-03-10 23:47:00+00:00,NaT,None,None,None,Male,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087414,1dd7bb2de9c3e8fc58962a25db518715b3cef54e_2026-...,1,DHDFNJ,1dd7bb2de9c3e8fc58962a25db518715b3cef54e,2026-03-10 23:57:00+00:00,NaT,None,None,None,Male,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087415,011a0c9d77115c9902c6b4f20667f2e2b75c85cb_2026-...,1,PLYMOMA,011a0c9d77115c9902c6b4f20667f2e2b75c85cb,2026-03-11 00:13:00+00:00,NaT,None,None,None,Male,...,NaT,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth
1087416,5a72db4bb17f84699ff794292f9dd0f5d86f12d9_2026-...,1,ELZICDF,5a72db4bb17f84699ff794292f9dd0f5d86f12d9,2026-03-11 00:30:00+00:00,NaT,None,None,None,Male,...,NaT,Elizabeth,NJ,Union,Elizabeth,NJ,Union,Elizabeth,NJ,Union

In [4]:
from datetime import datetime

In [5]:
df["stay_book_in_date_time"] = pd.to_datetime(df["stay_book_in_date_time"])

In [9]:
##siphoning just detentions made in the year of 2025

dfDetentions = df.loc[
  (df["stay_book_in_date_time"] >= "2025-01-01") &
  (df["stay_book_in_date_time"] <= "2025-12-31")]

In [10]:
dfDetentions

,stay_ID,n_stints,detention_facility_codes_all,unique_identifier,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,stay_release_reason,religion,gender,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
637420,3ae9dcfcad69c20a0f87f2244b428bab3fdf4c72_2025-...,3,STWRTGA; FIPCMGA; EROFCB,3ae9dcfcad69c20a0f87f2244b428bab3fdf4c72,2025-01-01 00:02:00+00:00,2025-10-06 18:38:00+00:00,2025-10-06,Removed,None,Male,...,2025-10-06 18:38:00+00:00,Lumpkin,GA,Stewart,Lumpkin,GA,Stewart,El Paso,TX,El Paso
637421,fc5236185a872f6498f7ae215b386df574ade0ea_2025-...,1,MTGPCTX,fc5236185a872f6498f7ae215b386df574ade0ea,2025-01-01 00:23:00+00:00,2025-01-13 09:00:00+00:00,2025-01-13,Removed,None,Male,...,2025-01-13 09:00:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Conroe,TX,Montgomery
637422,80e5c206d7ec272a512899b92f3df45066f97a93_2025-...,2,MTGPCTX; JCRLYTX,80e5c206d7ec272a512899b92f3df45066f97a93,2025-01-01 00:34:00+00:00,2025-02-07 08:00:00+00:00,2025-02-07,Removed,None,Male,...,2025-02-07 08:00:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Conroe,TX,Montgomery
637423,2ff541713ab2eb996c5d67c68fe2b036204324b2_2025-...,1,FSF,2ff541713ab2eb996c5d67c68fe2b036204324b2,2025-01-01 01:10:00+00:00,2025-01-01 08:48:00+00:00,2025-01-01,Removed,None,Male,...,2025-01-01 08:48:00+00:00,Florence,AZ,Pinal,Florence,AZ,Pinal,Florence,AZ,Pinal
637424,3fbb22c091ba28521ec0e62a25712fa262cbafcf_2025-...,1,FSF,3fbb22c091ba28521ec0e62a25712fa262cbafcf,2025-01-01 01:10:00+00:00,2025-01-01 08:48:00+00:00,2025-01-01,Removed,None,Male,...,2025-01-01 08:48:00+00:00,Florence,AZ,Pinal,Florence,AZ,Pinal,Florence,AZ,Pinal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1006405,eb54833555fd24dd084541cf68fd83bac113a035_2025-...,1,PINEPLA,eb54833555fd24dd084541cf68fd83bac113a035,2025-12-30 23:24:00+00:00,2026-01-03 12:17:00+00:00,2026-01-03,Removed,None,Male,...,2026-01-03 12:17:00+00:00,Pine Prairie,LA,Evangeline,Pine Prairie,LA,Evangeline,Pine Prairie,LA,Evangeline
1006406,68395fee90a7e07933ba3608ca2e14e1322c51a1_2025-...,1,EROFCB,68395fee90a7e07933ba3608ca2e14e1322c51a1,2025-12-30 23:31:00+00:00,2025-12-31 15:15:00+00:00,2025-12-31,Removed,None,Male,...,2025-12-31 15:15:00+00:00,El Paso,TX,El Paso,El Paso,TX,El Paso,El Paso,TX,El Paso
1006407,81d73fe202d8ae67e557dd60edc5ea62d285932b_2025-...,1,BOSHOLD,81d73fe202d8ae67e557dd60edc5ea62d285932b,2025-12-30 23:44:00+00:00,2025-12-30 23:47:00+00:00,2025-12-30,Order of recognizance,None,Female,...,2025-12-30 23:47:00+00:00,Burlington,MA,Middlesex,Burlington,MA,Middlesex,Burlington,MA,Middlesex
1006408,0fee0d3ee1ad46fc2821bbba0f83010d38f0292e_2025-...,2,LOSHOLD; ADLNTCA,0fee0d3ee1ad46fc2821bbba0f83010d38f0292e,2025-12-30 23:50:00+00:00,NaT,None,None,None,Male,...,NaT,Los Angeles,CA,Los Angeles,Adelanto,CA,San Bernardino,Adelanto,CA,San Bernardino
1006409,ce4662fbede551d17b1a0980a11cfc3cd976e935_2025-...,4,LOSHOLD; ADLNTCA; IWAHOLD; CCAFLAZ,ce4662fbede551d17b1a0980a11cfc3cd976e935,2025-12-31 00:00:00+00:00,2026-01-26 06:11:00+00:00,2026-01-26,Removed,None,Male,...,2026-01-26 06:11:00+00:00,Los Angeles,CA,Los Angeles,Adelanto,CA,San Bernardino,Florence,AZ,Pinal

In [12]:
dfArrestIDs = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/FilteredData/IDsNY2025Arrests_062326.csv')
dfArrestIDs

                              unique_identifier
0      baedf81fae1fd75a5f311ad042c51575fe127f35
1      254cce2f2a6ae9d741b12989c5501a0ff2c6b3ca
2      38b5ed10cf4cdb766b508bf9f09f79399c96d0ff
3      873861a4a6aa526918a4548de378a9cc23d6220f
4      a29f48cac1afb7324eb7f0ae26d5f27576a5cd56
...                                         ...
10966  bb9ecc5b3c48ea3392b39b335359417cc96756f2
10967  f3825b86ca6954770e3af431dd812083330e33e0
10968  e64f9b0e481ff3ba2f2970c4fad2c6870563a28b
10969  dd9306e1321f7485dddc8e2b2cf21bac052dd7b6
10970  ac68b01985954d30ce19b8887e2f3e13e5e02be0

[10971 rows x 1 columns]

In [22]:
#Now to sue the arrests identifier to only pull the detentions for arrests made in ny

filtered_detentions = dfDetentions[dfDetentions['unique_identifier'].isin(dfArrestIDs['unique_identifier'])]
filtered_detentions

,stay_ID,n_stints,detention_facility_codes_all,unique_identifier,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,stay_release_reason,religion,gender,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
637817,254cce2f2a6ae9d741b12989c5501a0ff2c6b3ca_2025-...,1,NYCHOLD,254cce2f2a6ae9d741b12989c5501a0ff2c6b3ca,2025-01-02 10:00:00+00:00,2025-01-02 13:00:00+00:00,2025-01-02,Order of Recognizance - Humanitarian,None,Female,...,2025-01-02 13:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
637818,38b5ed10cf4cdb766b508bf9f09f79399c96d0ff_2025-...,1,NYCHOLD,38b5ed10cf4cdb766b508bf9f09f79399c96d0ff,2025-01-02 10:00:00+00:00,2025-01-02 13:00:00+00:00,2025-01-02,Order of Recognizance - Humanitarian,None,Female,...,2025-01-02 13:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
637821,873861a4a6aa526918a4548de378a9cc23d6220f_2025-...,1,NYCHOLD,873861a4a6aa526918a4548de378a9cc23d6220f,2025-01-02 10:00:00+00:00,2025-01-02 13:00:00+00:00,2025-01-02,Order of Recognizance - Humanitarian,None,Male,...,2025-01-02 13:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
637822,a29f48cac1afb7324eb7f0ae26d5f27576a5cd56_2025-...,1,NYCHOLD,a29f48cac1afb7324eb7f0ae26d5f27576a5cd56,2025-01-02 10:00:00+00:00,2025-01-02 13:00:00+00:00,2025-01-02,Order of Recognizance - Humanitarian,None,Male,...,2025-01-02 13:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
637859,a5630b903129775297cad789755db52d04250c29_2025-...,1,NYCHOLD,a5630b903129775297cad789755db52d04250c29,2025-01-02 10:31:00+00:00,2025-01-02 12:15:00+00:00,2025-01-02,Order of recognizance,None,Female,...,2025-01-02 12:15:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1006365,1988658cf28bb11abc9633da06a3abf70bfea983_2025-...,1,CMDHOLD,1988658cf28bb11abc9633da06a3abf70bfea983,2025-12-30 21:55:00+00:00,NaT,None,None,None,Male,...,2025-12-31 09:28:00+00:00,None,NY,None,None,NY,None,None,NY,None
1006368,9afc2321af65b82e08b4a9a642a86e22baa007b0_2025-...,3,NYCHOLD; VRK; NYCHOLD,9afc2321af65b82e08b4a9a642a86e22baa007b0,2025-12-30 22:00:00+00:00,2025-12-31 18:22:00+00:00,2025-12-31,Transferred,None,Male,...,2025-12-31 18:22:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
1006369,b9c0c77df46c35040cced237b5bde4ca4f491286_2025-...,6,NYCHOLD; VRK; NYCHOLD; DHDFNJ; PIC; ADAMSMS,b9c0c77df46c35040cced237b5bde4ca4f491286,2025-12-30 22:00:00+00:00,NaT,None,None,None,Male,...,NaT,New York,NY,New York,Natchez,MS,Adams,Natchez,MS,Adams
1006370,5307997257056622d9cd3dfa4205fa1f9e629911_2025-...,6,NYCHOLD; VRK; NYCHOLD; DHDFNJ; PIC; ADAMSMS,5307997257056622d9cd3dfa4205fa1f9e629911,2025-12-30 22:19:00+00:00,2026-01-22 09:00:00+00:00,2026-01-22,Removed,None,Male,...,2026-01-22 09:00:00+00:00,New York,NY,New York,Natchez,MS,Adams,Natchez,MS,Adams
1006376,7e986789f8df3fcbd1ee65d0e79879d0c0119dd4_2025-...,1,CMDHOLD,7e986789f8df3fcbd1ee65d0e79879d0c0119dd4,2025-12-30 22:35:00+00:00,NaT,None,None,None,Male,...,2025-12-31 09:28:00+00:00,None,NY,None,None,NY,None,None,NY,None

In [23]:
filtered_detentions.to_csv('Filtereddata/2025DetentionsofNYArrests_062326.csv', index = False)

In [24]:
appear = filtered_detentions['unique_identifier'].value_counts()
appear

97f564fc0cf6b70d623cbec9feb38226b48ccfb9    3
685663b09aa09edebe1174d45abe6ed5033326f2    3
049184c63b97ee0c2d5bf8691383ee3506d444cb    3
3d84311c9a0df42fc5270f3a470c57ec4475d211    3
e9580fd5a2982049f9700a5ec593504781d20b7b    3
                                           ..
b2175219f56b16a1a519fd293497f4248f25879f    1
64e37ed2664ef6044fdee72d846177e91ea30b16    1
0291b743e14dda7d67ac06a5eb8ebd53bee09dbe    1
4ee14f9ba0d4e83093d122884cad79db2162024f    1
7e986789f8df3fcbd1ee65d0e79879d0c0119dd4    1
Name: unique_identifier, Length: 10505, dtype: int64

In [29]:
duplicates_only = appear[appear > 1]
print(duplicates_only)

97f564fc0cf6b70d623cbec9feb38226b48ccfb9    3
685663b09aa09edebe1174d45abe6ed5033326f2    3
049184c63b97ee0c2d5bf8691383ee3506d444cb    3
3d84311c9a0df42fc5270f3a470c57ec4475d211    3
e9580fd5a2982049f9700a5ec593504781d20b7b    3
                                           ..
1a5b57955af46aeb842c0151c29394b998a7af20    2
cb12f10001dc9ebc942a2906cb2d999bed25e84b    2
d7de3846f960daa5c03215cd5e454a07f2e82ae5    2
77a2f4baedff79dd78f4d4555b2146b611afa9a9    2
7cebdc44925a441e757b995914ca84547d579531    2
Name: unique_identifier, Length: 243, dtype: int64

In [27]:
duplicates_only = appear[appear > 2]
print(duplicates_only)

97f564fc0cf6b70d623cbec9feb38226b48ccfb9    3
685663b09aa09edebe1174d45abe6ed5033326f2    3
049184c63b97ee0c2d5bf8691383ee3506d444cb    3
3d84311c9a0df42fc5270f3a470c57ec4475d211    3
e9580fd5a2982049f9700a5ec593504781d20b7b    3
d702cd683a232a40680986ad44edc7744990d8bb    3
dfaa53a67218bfa4cfd2c8e93fbb8238ab44378f    3
fabb65aa95e49eb46c84dc710ffda5d00cfb2000    3
91598b461126ca864865bf697ab9c78f15caba2b    3
Name: unique_identifier, dtype: int64