In [1]:
import pandas as pd

In [2]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\sshrestha\appdata\local\anaconda3\lib\site-packages (21.0.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
##pulling in the data we got into this notebook
df = pd.read_csv(r"C:\Users\sshrestha\Desktop\Writing\DataProjects\ICE Deportations and Arrests\2024 Data\FilteredData\2024NYArrests_072226.csv", low_memory=False)
df

,apprehension_date,apprehension_state_filled_in,apprehension_aor,final_program,apprehension_method,apprehension_criminality,case_status,case_category,departure_country,final_order_yes_no,...,case_threat_level,unique_identifier,apprehension_date_time,duplicate_episode_identifier,duplicate_episode_first,duplicate_likely,duplicate_drop_row,file_original,sheet_original,row_original
0,11/4/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8C] Excludable / Inadmissible - Administrativ...,NaN,YES,...,NaN,0009f9ba7cc635f7620fd6d2b0be86f968c04d71,2024-11-04 09:34:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,42
1,9/25/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,NaN,000e00362a7ce05a098386f88e81e146cef564b8,2024-09-25 10:11:04+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,43
2,1/18/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,NaN,00119da62775f775fc6b28dbb06716f7306d6060,2024-01-18 12:49:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,49
3,4/16/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,NaN,00143e74440995cd4e3e78c3db761ed59cd82db5,2024-04-16 10:38:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,52
4,4/22/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,NaN,0026771284ae9e758f97c7b8b95ad0032990f3bb,2024-04-22 11:17:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4067,3/22/2024,NEW YORK,Buffalo Area of Responsibility,ERO Criminal Alien Program,CAP State Incarceration,1 Convicted Criminal,ACTIVE,[16] Reinstated Final Order,NaN,YES,...,1.0,ffeb4fd4dff55ed3b996bd1e935f7a443be1fe22,2024-03-22 08:04:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,112330
4068,1/30/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,HONDURAS,YES,...,NaN,fff8f3ae1841b2023ed0a646483fb585dcc7360a,2024-01-30 11:36:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,112357
4069,2/29/2024,NEW YORK,Buffalo Area of Responsibility,ERO Criminal Alien Program,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,[3] Deportable - Administratively Final Order,EL SALVADOR,YES,...,1.0,fffa9541d55830bab785c5a5b78cacf6fda28cfe,2024-02-29 07:37:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,112362
4070,5/15/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,NaN,fffc1c12e37bccf2693b5deb67a7f40b3744b156,2024-05-15 09:55:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,112366
4071,4/23/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,NaN,fffd8cddaedf2db4e037b8421d8bf22ae75a15fd,2024-04-23 11:00:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,112371

In [4]:
df_UI = df['unique_identifier']
df_UI

0       0009f9ba7cc635f7620fd6d2b0be86f968c04d71
1       000e00362a7ce05a098386f88e81e146cef564b8
2       00119da62775f775fc6b28dbb06716f7306d6060
3       00143e74440995cd4e3e78c3db761ed59cd82db5
4       0026771284ae9e758f97c7b8b95ad0032990f3bb
                          ...
4067    ffeb4fd4dff55ed3b996bd1e935f7a443be1fe22
4068    fff8f3ae1841b2023ed0a646483fb585dcc7360a
4069    fffa9541d55830bab785c5a5b78cacf6fda28cfe
4070    fffc1c12e37bccf2693b5deb67a7f40b3744b156
4071    fffd8cddaedf2db4e037b8421d8bf22ae75a15fd
Name: unique_identifier, Length: 4072, dtype: object

In [5]:
df_UI2 = df_UI.to_frame()
df_UI2

                             unique_identifier
0     0009f9ba7cc635f7620fd6d2b0be86f968c04d71
1     000e00362a7ce05a098386f88e81e146cef564b8
2     00119da62775f775fc6b28dbb06716f7306d6060
3     00143e74440995cd4e3e78c3db761ed59cd82db5
4     0026771284ae9e758f97c7b8b95ad0032990f3bb
...                                        ...
4067  ffeb4fd4dff55ed3b996bd1e935f7a443be1fe22
4068  fff8f3ae1841b2023ed0a646483fb585dcc7360a
4069  fffa9541d55830bab785c5a5b78cacf6fda28cfe
4070  fffc1c12e37bccf2693b5deb67a7f40b3744b156
4071  fffd8cddaedf2db4e037b8421d8bf22ae75a15fd

[4072 rows x 1 columns]

In [6]:
df_RAWDetentions = pd.read_parquet(r"C:\Users\sshrestha\Desktop\Writing\DataProjects\ICE Deportations and Arrests\2024 Data\RAWDATA\detention-stays-latest(1).parquet")
df_RAWDetentions

,stay_ID,n_stints,detention_facility_codes_all,initial_bond_set_amount_lowest_seen,initial_bond_set_date_earliest_seen,bond_posted_amount_lowest_seen,bond_posted_date_earliest_seen,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
0,33342b2832acf82179e0df53a43d957099d262e4_2004-...,2,JCRLYTX; JCRLYTX,NaN,None,NaN,NaT,2004-12-05 22:30:00+00:00,2025-01-23 22:30:00+00:00,2025-01-23,...,2025-01-23 22:30:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Conroe,TX,Montgomery
1,de10c6a3d0027b9a7bf15e7ae0726e67f733bd81_2011-...,4,YORCOPA; MIAHOLD; FLDSSFS; KRO,1500.0,2020-10-26,1500.0,2011-02-18 00:00:00+00:00,2011-01-11 23:59:00+00:00,NaT,None,...,NaT,York,PA,York,York,PA,York,Miami,FL,Miami-Dade
2,ad00adabb36933a9ae532721b36b572b7a70b09f_2011-...,2,ECC; PIC,NaN,None,NaN,NaT,2011-05-11 13:00:35+00:00,2026-02-10 02:58:00+00:00,2026-02-10,...,2026-02-10 02:58:00+00:00,El Centro,CA,Imperial,El Centro,CA,Imperial,Los Fresnos,TX,Cameron
3,20acf28b12065c2144c5106fab1698f79c43a7a2_2012-...,3,HOUHOLD; MTGHOLD; MTGPCTX,NaN,None,NaN,NaT,2012-11-06 09:43:00+00:00,2026-01-27 12:00:00+00:00,2026-01-27,...,2026-01-27 12:00:00+00:00,Houston,TX,Harris,Houston,TX,Harris,Conroe,TX,Montgomery
4,367c0c726a1428444b6aefdbd0f6a2b877ad0f2f_2014-...,2,FREHOLD; LOSHOLD,NaN,None,NaN,NaT,2014-01-17 13:18:00+00:00,2025-02-08 05:28:00+00:00,2025-02-08,...,2025-02-08 05:28:00+00:00,None,CA,None,None,CA,None,Los Angeles,CA,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087412,6cece9f08499216f65ba3be7200e5bdb6b7add7e_2026-...,1,SJS,NaN,None,NaN,NaT,2026-03-10 23:40:00+00:00,NaT,None,...,NaT,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo
1087413,a9792bfd2c9dc036a74e802047f3f9ee958892c1_2026-...,1,DHDFNJ,NaN,None,NaN,NaT,2026-03-10 23:47:00+00:00,NaT,None,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087414,1dd7bb2de9c3e8fc58962a25db518715b3cef54e_2026-...,1,DHDFNJ,NaN,None,NaN,NaT,2026-03-10 23:57:00+00:00,NaT,None,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087415,011a0c9d77115c9902c6b4f20667f2e2b75c85cb_2026-...,1,PLYMOMA,12000.0,None,1500.0,2012-05-18 00:00:00+00:00,2026-03-11 00:13:00+00:00,NaT,None,...,NaT,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth
1087416,5a72db4bb17f84699ff794292f9dd0f5d86f12d9_2026-...,1,ELZICDF,NaN,None,NaN,NaT,2026-03-11 00:30:00+00:00,NaT,None,...,NaT,Elizabeth,NJ,Union,Elizabeth,NJ,Union,Elizabeth,NJ,Union

In [7]:
##now wwe ask the notebook to use these unique identifiers to pull only those from the detentions list

filtered_detentions = df_RAWDetentions[df_RAWDetentions['unique_identifier'].isin(df_UI2['unique_identifier'])]
filtered_detentions

,stay_ID,n_stints,detention_facility_codes_all,initial_bond_set_amount_lowest_seen,initial_bond_set_date_earliest_seen,bond_posted_amount_lowest_seen,bond_posted_date_earliest_seen,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
4048,86148c3c29afdc6c4a61d58af7e91839825f30c5_2022-...,2,MSVPCPA; JENATLA,NaN,None,NaN,NaT,2022-06-23 13:00:00+00:00,2022-10-06 09:44:00+00:00,2022-10-06,...,2022-10-06 09:44:00+00:00,Philipsburg,PA,Clearfield,Philipsburg,PA,Clearfield,Alexandria,LA,Rapides
6017,9813a20b53de596e0f8b0e1214b87abf728abf97_2022-...,1,JKPCCLA,NaN,None,NaN,NaT,2022-07-21 09:50:00+00:00,2022-12-02 17:36:00+00:00,2022-12-02,...,2022-12-02 17:36:00+00:00,Jonesboro,LA,Jackson,Jonesboro,LA,Jackson,Jonesboro,LA,Jackson
15412,ae5b25cdaaf6b4293df86fdf8115d23131474f96_2022-...,1,CCAHUTX,NaN,None,NaN,NaT,2022-09-07 19:43:00+00:00,2022-11-16 11:00:00+00:00,2022-11-16,...,2022-11-16 11:00:00+00:00,Taylor,TX,Williamson,Taylor,TX,Williamson,Taylor,TX,Williamson
18693,1c9258e97b0e9baf905258c515582e49bb826d75_2022-...,1,CCASDCA,NaN,None,NaN,NaT,2022-09-19 08:37:00+00:00,2022-11-16 20:52:00+00:00,2022-11-16,...,2022-11-16 20:52:00+00:00,San Diego,CA,San Diego,San Diego,CA,San Diego,San Diego,CA,San Diego
24180,0f99ae360d7ed09c52ffb8e302f3765cda52d6a4_2022-...,2,EAZ; CSCNWWA,8500.0,None,8500.0,2024-11-12 00:00:00+00:00,2022-09-29 09:15:00+00:00,2022-10-11 16:35:00+00:00,2022-10-11,...,2022-10-11 16:35:00+00:00,Eloy,AZ,Pinal,Tacoma,WA,Pierce,Tacoma,WA,Pierce
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1071942,d3016e6b050c9068cec5bf81c541c15906c8bc4b_2026-...,4,PHIHOLD; BOPPHL; MSVPCPA; JENATLA,NaN,None,NaN,NaT,2026-02-24 15:34:00+00:00,2026-03-03 06:56:00+00:00,2026-03-03,...,2026-03-03 06:56:00+00:00,None,PA,None,Alexandria,LA,Rapides,Alexandria,LA,Rapides
1076292,6b9782d4437b71ab041865fba09288d556abbe86_2026-...,3,BTV; JENATLA; JKPCCLA,NaN,None,NaN,NaT,2026-02-27 16:33:00+00:00,NaT,None,...,NaT,Batavia,NY,Genesee,Batavia,NY,Genesee,Jonesboro,LA,Jackson
1076387,45512e1c268f823b3c7620da85e298416249333b_2026-...,1,ELZICDF,NaN,None,NaN,NaT,2026-02-27 22:06:00+00:00,NaT,None,...,NaT,Elizabeth,NJ,Union,Elizabeth,NJ,Union,Elizabeth,NJ,Union
1078685,f98415692f66168ef505a4ad6e300045c6cd2a1b_2026-...,3,BOSHOLD; STRAFNH; LAWINCI,NaN,None,NaN,NaT,2026-03-02 16:01:00+00:00,NaT,None,...,NaT,Burlington,MA,Middlesex,Winnfield,LA,Winn,Winnfield,LA,Winn
1081491,e89dc241785c56ae5b25cf4b310f9ac40de41ddc_2026-...,2,NYCHOLD; ORANGNY,NaN,None,NaN,NaT,2026-03-04 20:11:00+00:00,NaT,None,...,NaT,New York,NY,New York,Goshen,NY,Orange,Goshen,NY,Orange

In [8]:
##merge the two dataframes on unique identifier
ArrestsDetentions = pd.merge(df, filtered_detentions, on="unique_identifier")
ArrestsDetentions

,apprehension_date,apprehension_state_filled_in,apprehension_aor,final_program_x,apprehension_method,apprehension_criminality,case_status_x,case_category_x,departure_country_x,final_order_yes_no_x,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
0,11/4/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8C] Excludable / Inadmissible - Administrativ...,NaN,YES,...,2024-11-04 13:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
1,9/25/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,2024-09-25 11:07:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
2,1/18/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,2024-01-18 16:06:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
3,4/16/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,2024-04-16 14:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
4,4/22/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,2024-04-22 12:45:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3998,1/30/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,HONDURAS,YES,...,2024-01-30 14:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
3999,1/30/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,HONDURAS,YES,...,2025-11-15 11:49:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
4000,2/29/2024,NEW YORK,Buffalo Area of Responsibility,ERO Criminal Alien Program,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,[3] Deportable - Administratively Final Order,EL SALVADOR,YES,...,2024-03-22 09:09:00+00:00,Batavia,NY,Genesee,Batavia,NY,Genesee,Alexandria,LA,Rapides
4001,5/15/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,2024-05-15 11:12:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
4002,4/23/2024,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,...,2024-04-23 14:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York

In [9]:
ArrestsDetentions['unique_identifier'].value_counts()

unique_identifier
c49684bdf6b6f3b1110627341b5db57df7aff218    12
8f3d67781823da48df19fa928007437a28df9de3     4
5a4d25445e4886682d398fc0e742481ef0df6417     4
66708a3b7b20e1bc4b78b71ac8475982b19004f1     4
c3323f83060b975364a28ae665c98f5d24415f26     4
                                            ..
5a7240fdbc07b9823174f88a79b24b3d30fc2c9f     1
5a73ddc6e5a39071c130e5c3f5b97a7dba272084     1
5a8b0fcc27b68b0a33815a4effb26457e5afa28b     1
5a8d259169f59e7a1a82e1b4057d94ce884f6232     1
fffd8cddaedf2db4e037b8421d8bf22ae75a15fd     1
Name: count, Length: 3629, dtype: int64

In [10]:
ArrestsDetentions.to_csv('Filtereddata/2024ArrestsDetentions_072326.csv', index = False)