In [1]:
import pandas as pd

In [2]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\sshrestha\appdata\local\anaconda3\lib\site-packages (21.0.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
##let's bring in the raw data to the front
df = pd.read_parquet(r'C:\Users\sshrestha\Desktop\Writing\DataProjects\ICE Deportations and Arrests\2024 Data\RAWDATA\arrests-latest.parquet')
df

,apprehension_date,apprehension_type,apprehension_state_filled_in,apprehension_state_original,apprehension_aor,final_program,arresting_agency,apprehension_method,apprehension_criminality,case_status,...,case_threat_level,unique_identifier,apprehension_date_time,duplicate_episode_identifier,duplicate_episode_first,duplicate_likely,duplicate_drop_row,file_original,sheet_original,row_original
0,2025-11-16,Targeted,TEXAS,TEXAS,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,NA,0000004d7b875782a3b6f2b460f98c0750a5a899,2025-11-16 14:21:59+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,8
1,2025-09-17,Targeted,TEXAS,TEXAS,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,6-Deported/Removed - Deportability,...,NA,0000215186a4071ae5bc250f63e6baa60b286c30,2025-09-17 11:34:21+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,8
2,2022-10-05,None,NEW YORK,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NA,00002880c7d1c7fc09144a3fe22a5b45c5c204a6,2022-10-05 11:08:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY23_20260311_Redacted...,FY2023,8
3,2023-05-09,None,NEW YORK,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NA,00002d45a605af4dcf152d154a394bc4a8ac57c4,2023-05-09 11:11:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY23_20260311_Redacted...,FY2023,9
4,2023-11-06,None,ARKANSAS,None,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NA,00003080dc4054b217a897a57ae274a7585563bd,2023-11-06 13:36:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
713459,2026-03-10,Collateral,TEXAS,TEXAS,Harlingen Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,NA,None,2026-03-10 17:07:39+00:00,1,True,None,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,191549
713460,2026-03-10,Collateral,TEXAS,TEXAS,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,NA,None,2026-03-10 17:22:39+00:00,1,True,None,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,191550
713461,2026-03-10,Collateral,TEXAS,TEXAS,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,NA,None,2026-03-10 17:21:11+00:00,1,True,None,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,191551
713462,2026-03-10,Collateral,TEXAS,TEXAS,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,None,...,None,None,2026-03-10 16:14:39+00:00,1,True,None,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,191552
713463,2026-03-10,None,ILLINOIS,None,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,None,...,None,None,2026-03-10 18:26:43+00:00,1,True,None,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,191553

In [7]:
from datetime import datetime

In [8]:
#let's turn the apprehension date, the dat that will tell us when someone was arrested
#into a date format so we can use filters and other formulas on it. 

df["apprehension_date"] = pd.to_datetime(df["apprehension_date"])

In [10]:
##now let's use that apprehension date and state columns to pull only arrests made in 2024 within NYS

dfArrests = df.loc[
  (df["apprehension_date"] >= "2024-01-01") &
  (df["apprehension_date"] <= "2024-12-31") &
  (df["apprehension_state_filled_in"] == "NEW YORK")
]

dfArrests

,apprehension_date,apprehension_type,apprehension_state_filled_in,apprehension_state_original,apprehension_aor,final_program,arresting_agency,apprehension_method,apprehension_criminality,case_status,...,case_threat_level,unique_identifier,apprehension_date_time,duplicate_episode_identifier,duplicate_episode_first,duplicate_likely,duplicate_drop_row,file_original,sheet_original,row_original
121,2024-11-04,None,NEW YORK,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NA,0009f9ba7cc635f7620fd6d2b0be86f968c04d71,2024-11-04 09:34:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,42
164,2024-09-25,None,NEW YORK,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NA,000e00362a7ce05a098386f88e81e146cef564b8,2024-09-25 10:11:04+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,43
197,2024-01-18,None,NEW YORK,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NA,00119da62775f775fc6b28dbb06716f7306d6060,2024-01-18 12:49:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,49
224,2024-04-16,None,NEW YORK,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NA,00143e74440995cd4e3e78c3db761ed59cd82db5,2024-04-16 10:38:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,52
411,2024-04-22,None,NEW YORK,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NA,0026771284ae9e758f97c7b8b95ad0032990f3bb,2024-04-22 11:17:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
698866,2024-03-22,None,NEW YORK,NEW YORK,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,ACTIVE,...,1,ffeb4fd4dff55ed3b996bd1e935f7a443be1fe22,2024-03-22 08:04:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,112330
699023,2024-01-30,None,NEW YORK,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,NA,fff8f3ae1841b2023ed0a646483fb585dcc7360a,2024-01-30 11:36:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,112357
699045,2024-02-29,None,NEW YORK,NEW YORK,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,1,fffa9541d55830bab785c5a5b78cacf6fda28cfe,2024-02-29 07:37:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,112362
699073,2024-05-15,None,NEW YORK,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NA,fffc1c12e37bccf2693b5deb67a7f40b3744b156,2024-05-15 09:55:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,112366
699093,2024-04-23,None,NEW YORK,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NA,fffd8cddaedf2db4e037b8421d8bf22ae75a15fd,2024-04-23 11:00:00+00:00,1,True,False,False,2026-ICLI-00005_Arrests_FY24_20260311_Redacted...,FY2024,112371

In [12]:
##let's save those arrests
dfArrests.to_csv('FilteredData/2024NYArrests_072226.csv', index = False)

In [13]:
##we need to grab the unique identifier because that is how we will grab what we need from the detentions sheet
##it works as an "index" of sorts
dfIDsArrests = dfArrests[['unique_identifier']]

In [14]:
dfIDsArrests.to_csv('Filtereddata/IDsNY2024Arrests_072226.csv', index = False)