### In this notebook I will:
1. Pull the clean filtered data from arrests (that has removed duplicates and blank identifiers)
2. Use the unique identifiers there to cut through the raw parquet data of detentions
3. Join the clean filtered arrests data and the new filtered detentions data on the unique identifier data

In [1]:
import pandas as pd

In [2]:
pip install pyarrow

Requirement already satisfied: pyarrow in /Users/sajinashrestha/opt/anaconda3/lib/python3.9/site-packages (21.0.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
##pulling in the data we got into this notebook
df = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/FilteredData/2025NYArrests_070626.csv', low_memory=False)
df

,apprehension_date,apprehension_aor,final_program,apprehension_method,apprehension_criminality,case_status,case_category,departure_country,final_order_yes_no,age,...,apprehension_site_landmark,toa_current_duty_site,case_criminality,case_threat_level,unique_identifier,apprehension_date_time,duplicate_likely,file_original,sheet_original,row_original
0,1/2/2025,Buffalo Area of Responsibility,ERO Criminal Alien Program,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,HONDURAS,YES,34,...,FEDERAL CORRECTIONAL INSTITUTE RAY BROOK,"ERO - Champlain, NY Sub-Office",1 Convicted Criminal,1.0,baedf81fae1fd75a5f311ad042c51575fe127f35,2025-01-02 09:00:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,169580
1,1/2/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8C] Excludable / Inadmissible - Administrativ...,NaN,YES,19,...,"NDD - 26 FEDERAL PLAZA NY, NY","NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,254cce2f2a6ae9d741b12989c5501a0ff2c6b3ca,2025-01-02 09:32:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,33838
2,1/2/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,MEXICO,YES,37,...,"NDD - 26 FEDERAL PLAZA NY, NY","NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,38b5ed10cf4cdb766b508bf9f09f79399c96d0ff,2025-01-02 09:39:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,51499
3,1/2/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,MEXICO,YES,8,...,"NDD - 26 FEDERAL PLAZA NY, NY","NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,873861a4a6aa526918a4548de378a9cc23d6220f,2025-01-02 10:00:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,122696
4,1/2/2025,New York City Area of Responsibility,Non-Detained Docket Control,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,MEXICO,YES,6,...,"NDD - 26 FEDERAL PLAZA NY, NY","NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,a29f48cac1afb7324eb7f0ae26d5f27576a5cd56,2025-01-02 10:10:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,147470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10769,12/31/2025,New York City Area of Responsibility,Fugitive Operations,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,GUATEMALA,YES,30,...,FUGITIVE OPERATIONS NY STATE,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,bb9ecc5b3c48ea3392b39b335359417cc96756f2,2025-12-31 15:35:57+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,134863
10770,12/31/2025,Buffalo Area of Responsibility,Fugitive Operations,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,NaN,NO,29,...,MONROE COUNTY,BATAVIA CMD CTR NY DCO,3 Other Immigration Violator,NaN,f3825b86ca6954770e3af431dd812083330e33e0,2025-12-31 16:16:15+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,175277
10771,12/31/2025,New York City Area of Responsibility,Alternatives to Detention,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,ECUADOR,YES,36,...,"CIP GENERAL AREA, NON-SPECIFIC","ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NaN,e64f9b0e481ff3ba2f2970c4fad2c6870563a28b,2025-12-31 22:30:00+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,165653
10772,12/31/2025,New York City Area of Responsibility,Alternatives to Detention,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,PERU,YES,35,...,"CIP GENERAL AREA, NON-SPECIFIC","ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NaN,dd9306e1321f7485dddc8e2b2cf21bac052dd7b6,2025-12-31 22:45:04+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,159286
10773,12/31/2025,New York City Area of Responsibility,Alternatives to Detention,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,PERU,YES,10,...,"CIP GENERAL AREA, NON-SPECIFIC","ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NaN,ac68b01985954d30ce19b8887e2f3e13e5e02be0,2025-12-31 23:05:25+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,123892

In [6]:
df_UI = df['unique_identifier']
df_UI

0        baedf81fae1fd75a5f311ad042c51575fe127f35
1        254cce2f2a6ae9d741b12989c5501a0ff2c6b3ca
2        38b5ed10cf4cdb766b508bf9f09f79399c96d0ff
3        873861a4a6aa526918a4548de378a9cc23d6220f
4        a29f48cac1afb7324eb7f0ae26d5f27576a5cd56
                           ...
10769    bb9ecc5b3c48ea3392b39b335359417cc96756f2
10770    f3825b86ca6954770e3af431dd812083330e33e0
10771    e64f9b0e481ff3ba2f2970c4fad2c6870563a28b
10772    dd9306e1321f7485dddc8e2b2cf21bac052dd7b6
10773    ac68b01985954d30ce19b8887e2f3e13e5e02be0
Name: unique_identifier, Length: 10774, dtype: object

In [7]:
df_RAWDetentions = pd.read_parquet('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/detention-stays-latest.parquet')
df_RAWDetentions

,stay_ID,n_stints,detention_facility_codes_all,unique_identifier,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,stay_release_reason,religion,gender,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
0,33342b2832acf82179e0df53a43d957099d262e4_2004-...,2,JCRLYTX; JCRLYTX,33342b2832acf82179e0df53a43d957099d262e4,2004-12-05 22:30:00+00:00,2025-01-23 22:30:00+00:00,2025-01-23,Removed,None,Male,...,2025-01-23 22:30:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Conroe,TX,Montgomery
1,de10c6a3d0027b9a7bf15e7ae0726e67f733bd81_2011-...,4,YORCOPA; MIAHOLD; FLDSSFS; KRO,de10c6a3d0027b9a7bf15e7ae0726e67f733bd81,2011-01-11 23:59:00+00:00,NaT,None,None,None,Male,...,NaT,York,PA,York,York,PA,York,Miami,FL,Miami-Dade
2,ad00adabb36933a9ae532721b36b572b7a70b09f_2011-...,2,ECC; PIC,ad00adabb36933a9ae532721b36b572b7a70b09f,2011-05-11 13:00:35+00:00,2026-02-10 02:58:00+00:00,2026-02-10,Removed,None,Male,...,2026-02-10 02:58:00+00:00,El Centro,CA,Imperial,El Centro,CA,Imperial,Los Fresnos,TX,Cameron
3,20acf28b12065c2144c5106fab1698f79c43a7a2_2012-...,3,HOUHOLD; MTGHOLD; MTGPCTX,20acf28b12065c2144c5106fab1698f79c43a7a2,2012-11-06 09:43:00+00:00,2026-01-27 12:00:00+00:00,2026-01-27,Removed,None,Male,...,2026-01-27 12:00:00+00:00,Houston,TX,Harris,Houston,TX,Harris,Conroe,TX,Montgomery
4,367c0c726a1428444b6aefdbd0f6a2b877ad0f2f_2014-...,2,FREHOLD; LOSHOLD,367c0c726a1428444b6aefdbd0f6a2b877ad0f2f,2014-01-17 13:18:00+00:00,2025-02-08 05:28:00+00:00,2025-02-08,Removed,None,Male,...,2025-02-08 05:28:00+00:00,None,CA,None,None,CA,None,Los Angeles,CA,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087412,6cece9f08499216f65ba3be7200e5bdb6b7add7e_2026-...,1,SJS,6cece9f08499216f65ba3be7200e5bdb6b7add7e,2026-03-10 23:40:00+00:00,NaT,None,None,None,Male,...,NaT,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo
1087413,a9792bfd2c9dc036a74e802047f3f9ee958892c1_2026-...,1,DHDFNJ,a9792bfd2c9dc036a74e802047f3f9ee958892c1,2026-03-10 23:47:00+00:00,NaT,None,None,None,Male,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087414,1dd7bb2de9c3e8fc58962a25db518715b3cef54e_2026-...,1,DHDFNJ,1dd7bb2de9c3e8fc58962a25db518715b3cef54e,2026-03-10 23:57:00+00:00,NaT,None,None,None,Male,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087415,011a0c9d77115c9902c6b4f20667f2e2b75c85cb_2026-...,1,PLYMOMA,011a0c9d77115c9902c6b4f20667f2e2b75c85cb,2026-03-11 00:13:00+00:00,NaT,None,None,None,Male,...,NaT,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth
1087416,5a72db4bb17f84699ff794292f9dd0f5d86f12d9_2026-...,1,ELZICDF,5a72db4bb17f84699ff794292f9dd0f5d86f12d9,2026-03-11 00:30:00+00:00,NaT,None,None,None,Male,...,NaT,Elizabeth,NJ,Union,Elizabeth,NJ,Union,Elizabeth,NJ,Union