In [1]:
import pandas as pd

In [2]:
pip install pyarrow

Requirement already satisfied: pyarrow in /Users/sajinashrestha/opt/anaconda3/lib/python3.9/site-packages (21.0.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
df = pd.read_parquet('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/detention-stays-latest.parquet')
df

,stay_ID,n_stints,detention_facility_codes_all,unique_identifier,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,stay_release_reason,religion,gender,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
0,33342b2832acf82179e0df53a43d957099d262e4_2004-...,2,JCRLYTX; JCRLYTX,33342b2832acf82179e0df53a43d957099d262e4,2004-12-05 22:30:00+00:00,2025-01-23 22:30:00+00:00,2025-01-23,Removed,None,Male,...,2025-01-23 22:30:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Conroe,TX,Montgomery
1,de10c6a3d0027b9a7bf15e7ae0726e67f733bd81_2011-...,4,YORCOPA; MIAHOLD; FLDSSFS; KRO,de10c6a3d0027b9a7bf15e7ae0726e67f733bd81,2011-01-11 23:59:00+00:00,NaT,None,None,None,Male,...,NaT,York,PA,York,York,PA,York,Miami,FL,Miami-Dade
2,ad00adabb36933a9ae532721b36b572b7a70b09f_2011-...,2,ECC; PIC,ad00adabb36933a9ae532721b36b572b7a70b09f,2011-05-11 13:00:35+00:00,2026-02-10 02:58:00+00:00,2026-02-10,Removed,None,Male,...,2026-02-10 02:58:00+00:00,El Centro,CA,Imperial,El Centro,CA,Imperial,Los Fresnos,TX,Cameron
3,20acf28b12065c2144c5106fab1698f79c43a7a2_2012-...,3,HOUHOLD; MTGHOLD; MTGPCTX,20acf28b12065c2144c5106fab1698f79c43a7a2,2012-11-06 09:43:00+00:00,2026-01-27 12:00:00+00:00,2026-01-27,Removed,None,Male,...,2026-01-27 12:00:00+00:00,Houston,TX,Harris,Houston,TX,Harris,Conroe,TX,Montgomery
4,367c0c726a1428444b6aefdbd0f6a2b877ad0f2f_2014-...,2,FREHOLD; LOSHOLD,367c0c726a1428444b6aefdbd0f6a2b877ad0f2f,2014-01-17 13:18:00+00:00,2025-02-08 05:28:00+00:00,2025-02-08,Removed,None,Male,...,2025-02-08 05:28:00+00:00,None,CA,None,None,CA,None,Los Angeles,CA,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087412,6cece9f08499216f65ba3be7200e5bdb6b7add7e_2026-...,1,SJS,6cece9f08499216f65ba3be7200e5bdb6b7add7e,2026-03-10 23:40:00+00:00,NaT,None,None,None,Male,...,NaT,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo
1087413,a9792bfd2c9dc036a74e802047f3f9ee958892c1_2026-...,1,DHDFNJ,a9792bfd2c9dc036a74e802047f3f9ee958892c1,2026-03-10 23:47:00+00:00,NaT,None,None,None,Male,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087414,1dd7bb2de9c3e8fc58962a25db518715b3cef54e_2026-...,1,DHDFNJ,1dd7bb2de9c3e8fc58962a25db518715b3cef54e,2026-03-10 23:57:00+00:00,NaT,None,None,None,Male,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087415,011a0c9d77115c9902c6b4f20667f2e2b75c85cb_2026-...,1,PLYMOMA,011a0c9d77115c9902c6b4f20667f2e2b75c85cb,2026-03-11 00:13:00+00:00,NaT,None,None,None,Male,...,NaT,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth
1087416,5a72db4bb17f84699ff794292f9dd0f5d86f12d9_2026-...,1,ELZICDF,5a72db4bb17f84699ff794292f9dd0f5d86f12d9,2026-03-11 00:30:00+00:00,NaT,None,None,None,Male,...,NaT,Elizabeth,NJ,Union,Elizabeth,NJ,Union,Elizabeth,NJ,Union

In [4]:
from datetime import datetime

In [5]:
df["stay_book_in_date_time"] = pd.to_datetime(df["stay_book_in_date_time"])

In [9]:
##siphoning just detentions made in the year of 2025

dfDetentions = df.loc[
  (df["stay_book_in_date_time"] >= "2025-01-01") &
  (df["stay_book_in_date_time"] <= "2025-12-31")]

In [10]:
dfDetentions

,stay_ID,n_stints,detention_facility_codes_all,unique_identifier,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,stay_release_reason,religion,gender,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
637420,3ae9dcfcad69c20a0f87f2244b428bab3fdf4c72_2025-...,3,STWRTGA; FIPCMGA; EROFCB,3ae9dcfcad69c20a0f87f2244b428bab3fdf4c72,2025-01-01 00:02:00+00:00,2025-10-06 18:38:00+00:00,2025-10-06,Removed,None,Male,...,2025-10-06 18:38:00+00:00,Lumpkin,GA,Stewart,Lumpkin,GA,Stewart,El Paso,TX,El Paso
637421,fc5236185a872f6498f7ae215b386df574ade0ea_2025-...,1,MTGPCTX,fc5236185a872f6498f7ae215b386df574ade0ea,2025-01-01 00:23:00+00:00,2025-01-13 09:00:00+00:00,2025-01-13,Removed,None,Male,...,2025-01-13 09:00:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Conroe,TX,Montgomery
637422,80e5c206d7ec272a512899b92f3df45066f97a93_2025-...,2,MTGPCTX; JCRLYTX,80e5c206d7ec272a512899b92f3df45066f97a93,2025-01-01 00:34:00+00:00,2025-02-07 08:00:00+00:00,2025-02-07,Removed,None,Male,...,2025-02-07 08:00:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Conroe,TX,Montgomery
637423,2ff541713ab2eb996c5d67c68fe2b036204324b2_2025-...,1,FSF,2ff541713ab2eb996c5d67c68fe2b036204324b2,2025-01-01 01:10:00+00:00,2025-01-01 08:48:00+00:00,2025-01-01,Removed,None,Male,...,2025-01-01 08:48:00+00:00,Florence,AZ,Pinal,Florence,AZ,Pinal,Florence,AZ,Pinal
637424,3fbb22c091ba28521ec0e62a25712fa262cbafcf_2025-...,1,FSF,3fbb22c091ba28521ec0e62a25712fa262cbafcf,2025-01-01 01:10:00+00:00,2025-01-01 08:48:00+00:00,2025-01-01,Removed,None,Male,...,2025-01-01 08:48:00+00:00,Florence,AZ,Pinal,Florence,AZ,Pinal,Florence,AZ,Pinal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1006405,eb54833555fd24dd084541cf68fd83bac113a035_2025-...,1,PINEPLA,eb54833555fd24dd084541cf68fd83bac113a035,2025-12-30 23:24:00+00:00,2026-01-03 12:17:00+00:00,2026-01-03,Removed,None,Male,...,2026-01-03 12:17:00+00:00,Pine Prairie,LA,Evangeline,Pine Prairie,LA,Evangeline,Pine Prairie,LA,Evangeline
1006406,68395fee90a7e07933ba3608ca2e14e1322c51a1_2025-...,1,EROFCB,68395fee90a7e07933ba3608ca2e14e1322c51a1,2025-12-30 23:31:00+00:00,2025-12-31 15:15:00+00:00,2025-12-31,Removed,None,Male,...,2025-12-31 15:15:00+00:00,El Paso,TX,El Paso,El Paso,TX,El Paso,El Paso,TX,El Paso
1006407,81d73fe202d8ae67e557dd60edc5ea62d285932b_2025-...,1,BOSHOLD,81d73fe202d8ae67e557dd60edc5ea62d285932b,2025-12-30 23:44:00+00:00,2025-12-30 23:47:00+00:00,2025-12-30,Order of recognizance,None,Female,...,2025-12-30 23:47:00+00:00,Burlington,MA,Middlesex,Burlington,MA,Middlesex,Burlington,MA,Middlesex
1006408,0fee0d3ee1ad46fc2821bbba0f83010d38f0292e_2025-...,2,LOSHOLD; ADLNTCA,0fee0d3ee1ad46fc2821bbba0f83010d38f0292e,2025-12-30 23:50:00+00:00,NaT,None,None,None,Male,...,NaT,Los Angeles,CA,Los Angeles,Adelanto,CA,San Bernardino,Adelanto,CA,San Bernardino
1006409,ce4662fbede551d17b1a0980a11cfc3cd976e935_2025-...,4,LOSHOLD; ADLNTCA; IWAHOLD; CCAFLAZ,ce4662fbede551d17b1a0980a11cfc3cd976e935,2025-12-31 00:00:00+00:00,2026-01-26 06:11:00+00:00,2026-01-26,Removed,None,Male,...,2026-01-26 06:11:00+00:00,Los Angeles,CA,Los Angeles,Adelanto,CA,San Bernardino,Florence,AZ,Pinal

In [12]:
dfArrestIDs = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/FilteredData/IDsNY2025Arrests_062326.csv')
dfArrestIDs

                              unique_identifier
0      baedf81fae1fd75a5f311ad042c51575fe127f35
1      254cce2f2a6ae9d741b12989c5501a0ff2c6b3ca
2      38b5ed10cf4cdb766b508bf9f09f79399c96d0ff
3      873861a4a6aa526918a4548de378a9cc23d6220f
4      a29f48cac1afb7324eb7f0ae26d5f27576a5cd56
...                                         ...
10966  bb9ecc5b3c48ea3392b39b335359417cc96756f2
10967  f3825b86ca6954770e3af431dd812083330e33e0
10968  e64f9b0e481ff3ba2f2970c4fad2c6870563a28b
10969  dd9306e1321f7485dddc8e2b2cf21bac052dd7b6
10970  ac68b01985954d30ce19b8887e2f3e13e5e02be0

[10971 rows x 1 columns]

In [18]:
#Now to sue the arrests identifier to only pull the detentions for arrests made in ny

filtered_detentions = df[df['unique_identifier'].isin(dfArrestIDs['unique_identifier'])]
filtered_detentions

,stay_ID,n_stints,detention_facility_codes_all,unique_identifier,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,stay_release_reason,religion,gender,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
31,56ee25358945f67089e40922608ff2b1a1396a72_2018-...,1,CCASDCA,56ee25358945f67089e40922608ff2b1a1396a72,2018-12-31 17:32:00+00:00,2023-02-08 18:11:00+00:00,2023-02-08,Removed,None,Male,...,2023-02-08 18:11:00+00:00,San Diego,CA,San Diego,San Diego,CA,San Diego,San Diego,CA,San Diego
40,4e448daffa72171ce7670fe9aa17f98050fbe35c_2019-...,1,BTV,4e448daffa72171ce7670fe9aa17f98050fbe35c,2019-03-28 09:22:00+00:00,2024-04-05 15:00:00+00:00,2024-04-05,Order of recognizance,None,Male,...,2024-04-05 15:00:00+00:00,Batavia,NY,Genesee,Batavia,NY,Genesee,Batavia,NY,Genesee
226,2782c92f42cfa9b8dd7640b1de29652cce2ea682_2021-...,2,JENADLA; JENATLA,2782c92f42cfa9b8dd7640b1de29652cce2ea682,2021-02-26 13:10:00+00:00,2022-10-11 10:02:00+00:00,2022-10-11,Removed,None,Male,...,2022-10-11 10:02:00+00:00,Jena,LA,LaSalle,Jena,LA,LaSalle,Alexandria,LA,Rapides
267,5fd376c3b771aed2d9c5062f1eff801c2eacde07_2021-...,2,BOONEKY; LOUHOLD,5fd376c3b771aed2d9c5062f1eff801c2eacde07,2021-05-18 13:57:00+00:00,2022-12-16 12:54:00+00:00,2022-12-16,Order of Supervision - No SLRRFF,None,Male,...,2022-12-16 12:54:00+00:00,Burlington,KY,Boone,Burlington,KY,Boone,None,KY,None
1210,c1ca2efd571727208d4ca420bd905b998257b22b_2022-...,2,FIPCAGA; STWRTGA,c1ca2efd571727208d4ca420bd905b998257b22b,2022-03-18 08:10:00+00:00,2023-01-21 08:38:00+00:00,2023-01-21,Order of supervision,None,Male,...,2023-01-21 08:38:00+00:00,Folkston,GA,Charlton,Folkston,GA,Charlton,Lumpkin,GA,Stewart
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075482,dc5fc5f142cd5389ec60fe7f9706d67660fac357_2026-...,1,IRADFCA,dc5fc5f142cd5389ec60fe7f9706d67660fac357,2026-02-27 09:00:00+00:00,NaT,None,None,None,Male,...,NaT,Calexico,CA,Imperial,Calexico,CA,Imperial,Calexico,CA,Imperial
1080650,1a4039c889e5cc4ca85935e4ed449d5968455202_2026-...,3,MADISNY; SYRHOLD; BTV,1a4039c889e5cc4ca85935e4ed449d5968455202,2026-03-04 10:01:00+00:00,NaT,None,None,None,Male,...,NaT,Wampsville,NY,Madison,Batavia,NY,Genesee,Batavia,NY,Genesee
1082764,ed2daa1af058ed646b8009f6ae3d06a7ea592232_2026-...,2,NYCHOLD; ORANGNY,ed2daa1af058ed646b8009f6ae3d06a7ea592232,2026-03-05 21:22:00+00:00,2026-03-09 09:48:00+00:00,2026-03-09,U.S. Marshals or other agency (explain in Dete...,None,Male,...,2026-03-09 09:48:00+00:00,New York,NY,New York,Goshen,NY,Orange,Goshen,NY,Orange
1085696,f4972aa253091956922a5db8ac6dbae3dd62fbb3_2026-...,1,NYCHOLD,f4972aa253091956922a5db8ac6dbae3dd62fbb3,2026-03-09 12:28:00+00:00,2026-03-10 18:15:00+00:00,2026-03-10,Transferred,None,Male,...,2026-03-10 18:15:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
1086849,85021aab1d8e0c5705721e610ecae6241ad259e6_2026-...,2,NYCHOLD; ORANGNY,85021aab1d8e0c5705721e610ecae6241ad259e6,2026-03-10 12:22:00+00:00,NaT,None,None,None,Male,...,NaT,New York,NY,New York,New York,NY,New York,Goshen,NY,Orange

In [19]:
appear = filtered_detentions['unique_identifier'].value_counts()
appear

61c135f0c82009a40ac198e422bffef13a96a7aa    4
5ee3a6bfeba0000ece04d06ba23e92e2d455cb3d    4
98206cf85032613297b725b799b3ac695ce650c2    4
daecf320e93e1dae79c79dc6ede72c165f96fbf7    3
d3909ba68e4366bcfa3df889841b23002614506e    3
                                           ..
4f52cd9e4639d20d8738b3b2bb9567c84f582585    1
3e3f487321c4261597304825a29453d23676b78e    1
f18f218a811e95f4094e72cfe38eb9667a4bea50    1
eaead8830b3e90c137b9bd425943dff63a4b3df5    1
a3ebd3c7e03e5929c76006a80300f179b92004c2    1
Name: unique_identifier, Length: 10559, dtype: int64

In [20]:
duplicates_only = appear[appear > 1]
print(duplicates_only)

61c135f0c82009a40ac198e422bffef13a96a7aa    4
5ee3a6bfeba0000ece04d06ba23e92e2d455cb3d    4
98206cf85032613297b725b799b3ac695ce650c2    4
daecf320e93e1dae79c79dc6ede72c165f96fbf7    3
d3909ba68e4366bcfa3df889841b23002614506e    3
                                           ..
1a526898e3ee625015b0a04c30451789c462690c    2
7a8a457bb802955632257f52fdae7750dc25220d    2
c516453ccd3843ac70418898214682516f54c25a    2
50d061933aca26f99d15096b97453e37636d5759    2
ad52eb79d219a1d0a7ef9d9b77c6f9a9f9ce7f3c    2
Name: unique_identifier, Length: 1235, dtype: int64