In [3]:
import pandas as pd

In [4]:
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-21.0.0-cp39-cp39-macosx_12_0_x86_64.whl.metadata (3.3 kB)
Downloading pyarrow-21.0.0-cp39-cp39-macosx_12_0_x86_64.whl (32.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.7/32.7 MB 18.3 MB/s  0:00:01 18.7 MB/s eta 0:00:01
Installing collected packages: pyarrow
Successfully installed pyarrow-21.0.0

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
df = pd.read_parquet('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICEpresense-CapitalRegion/RawData/arrests-latest.parquet')

In [8]:
df

,apprehension_date,apprehension_type,apprehension_state,apprehension_aor,final_program,arresting_agency,apprehension_method,apprehension_criminality,case_status,case_category,...,operation,toa_current_duty_site,case_criminality,case_threat_level,unique_identifier,apprehension_date_time,duplicate_likely,file_original,sheet_original,row_original
0,2022-10-01,None,TEXAS,San Antonio Area of Responsibility,Non-Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,A-Proceedings Terminated,[8B] Excludable / Inadmissible - Under Adjudic...,...,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NA,bad3911f91e15e59572fe96a226c1fdbcf82d799,2022-10-01 01:10:00+00:00,False,2026-ICLI-00005_Arrests_FY23_20260311_Redacted...,FY2023,124239
1,2022-10-01,None,None,Phoenix Area of Responsibility,Detained Docket Control,ICE,ERO Reprocessed Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,...,None,"ELOY, AZ, SERVICE PROCESSING CENTER (DOCKET CO...",1 Convicted Criminal,1,dafdb5d0e565d238b9093e99c42e305ac95ce2b4,2022-10-01 01:47:37+00:00,False,2026-ICLI-00005_Arrests_FY23_20260311_Redacted...,FY2023,145764
2,2022-10-01,None,None,Phoenix Area of Responsibility,Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,...,None,"ELOY, AZ, SERVICE PROCESSING CENTER (DOCKET CO...",3 Other Immigration Violator,NA,1db208374a6ce32dd03f1b6d876c9f692b756185,2022-10-01 02:52:47+00:00,False,2026-ICLI-00005_Arrests_FY23_20260311_Redacted...,FY2023,19899
3,2022-10-01,None,FLORIDA,Miami Area of Responsibility,287G Program,ICE,287(g) Program,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,...,HQ Tracking of Processing done by 287(g) autho...,Jacksonville Sheriff's Office,2 Pending Criminal Charges,NA,50198f8883c9b118a1153af301c65bfef03bb058,2022-10-01 03:05:00+00:00,False,2026-ICLI-00005_Arrests_FY23_20260311_Redacted...,FY2023,53227
4,2022-10-01,None,TEXAS,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,A-Proceedings Terminated,[8B] Excludable / Inadmissible - Under Adjudic...,...,None,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NA,84553a21705f50805c41fbdd55c26389e196df2e,2022-10-01 06:30:00+00:00,False,2026-ICLI-00005_Arrests_FY23_20260311_Redacted...,FY2023,88098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
713459,2026-03-10,Targeted,NEW JERSEY,Newark Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,2 Pending Criminal Charges,ACTIVE,[8A] Excludable / Inadmissible - Hearing Not C...,...,None,"NEWARK, NJ, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NA,b6e64f2f98dd51dfd782be1d3cb170e37faca696,2026-03-10 23:42:25+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,131343
713460,2026-03-10,Targeted,TEXAS,Houston Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,1 Convicted Criminal,None,None,...,None,"ERO - Montgomery County, TX Sub Office",None,None,3300c033883216554e0ca8bca139abba21bc05f8,2026-03-10 23:44:52+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,36826
713461,2026-03-10,Targeted,NEW JERSEY,Newark Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,ACTIVE,[8A] Excludable / Inadmissible - Hearing Not C...,...,None,"NEWARK, NJ, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,5a72db4bb17f84699ff794292f9dd0f5d86f12d9,2026-03-10 23:59:36+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,65026
713462,2026-03-11,Targeted,NEW JERSEY,Newark Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,2 Pending Criminal Charges,ACTIVE,[8A] Excludable / Inadmissible - Hearing Not C...,...,None,"NEWARK, NJ, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NA,8713c46d9d0d1ad64dbb4e957b602ce49ab878b4,2026-03-11 00:07:07+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,97263
713463,2026-09-17,Targeted,TEXAS,Dallas Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8D] Excludable / Inadmissible - Under Adjudic...,...,None,"DALLAS, TX, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NA,1b8a885bc5eba99f3b5aff0361be18da6d761241,2026-09-17 10:48:45+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,19824

In [10]:
from datetime import datetime

In [11]:
df["apprehension_date"] = pd.to_datetime(df["apprehension_date"])

In [12]:
##siphoning jsut arrests made in nystate in the year of 2025

dfArrests = df.loc[
  (df["apprehension_date"] >= "2025-01-01") &
  (df["apprehension_date"] <= "2025-12-31") &
  (df["apprehension_state"] == "NEW YORK")
]

dfArrests

,apprehension_date,apprehension_type,apprehension_state,apprehension_aor,final_program,arresting_agency,apprehension_method,apprehension_criminality,case_status,case_category,...,operation,toa_current_duty_site,case_criminality,case_threat_level,unique_identifier,apprehension_date_time,duplicate_likely,file_original,sheet_original,row_original
313423,2025-01-02,None,NEW YORK,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,...,None,"ERO - Champlain, NY Sub-Office",1 Convicted Criminal,1,baedf81fae1fd75a5f311ad042c51575fe127f35,2025-01-02 09:00:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,169580
313442,2025-01-02,None,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8C] Excludable / Inadmissible - Administrativ...,...,-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NA,254cce2f2a6ae9d741b12989c5501a0ff2c6b3ca,2025-01-02 09:32:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,33838
313449,2025-01-02,None,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,...,-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NA,38b5ed10cf4cdb766b508bf9f09f79399c96d0ff,2025-01-02 09:39:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,51499
313458,2025-01-02,None,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,...,-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NA,873861a4a6aa526918a4548de378a9cc23d6220f,2025-01-02 10:00:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,122696
313467,2025-01-02,None,NEW YORK,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,...,-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NA,a29f48cac1afb7324eb7f0ae26d5f27576a5cd56,2025-01-02 10:10:00+00:00,False,2026-ICLI-00005_Arrests_FY25_20260311_Redacted...,FY2025,147470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634847,2025-12-31,Collateral,NEW YORK,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,...,None,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NA,bb9ecc5b3c48ea3392b39b335359417cc96756f2,2025-12-31 15:35:57+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,134863
634879,2025-12-31,Targeted,NEW YORK,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,[8B] Excludable / Inadmissible - Under Adjudic...,...,None,BATAVIA CMD CTR NY DCO,3 Other Immigration Violator,NA,f3825b86ca6954770e3af431dd812083330e33e0,2025-12-31 16:16:15+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,175277
634964,2025-12-31,Targeted,NEW YORK,New York City Area of Responsibility,Alternatives to Detention,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,...,None,"ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NA,e64f9b0e481ff3ba2f2970c4fad2c6870563a28b,2025-12-31 22:30:00+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,165653
634968,2025-12-31,Targeted,NEW YORK,New York City Area of Responsibility,Alternatives to Detention,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,...,None,"ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NA,dd9306e1321f7485dddc8e2b2cf21bac052dd7b6,2025-12-31 22:45:04+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,159286
634969,2025-12-31,Targeted,NEW YORK,New York City Area of Responsibility,Alternatives to Detention,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,...,None,"ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NA,ac68b01985954d30ce19b8887e2f3e13e5e02be0,2025-12-31 23:05:25+00:00,False,2026-ICLI-00005_Arrests_FY26_20260311_Redacted...,FY2026,123892

In [13]:
dfArrests.to_csv('FilteredData/2025NYArrests_062326.csv', index = False)