In [4]:
import pandas as pd

In [5]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\sshrestha\appdata\local\anaconda3\lib\site-packages (21.0.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
##pulling in the data we got into this notebook
df = pd.read_parquet(r"C:\Users\sshrestha\Desktop\Writing\DataProjects\ICE Deportations and Arrests\2024 Data\RAWDATA\detention-stays-latest(1).parquet")
df

,stay_ID,n_stints,detention_facility_codes_all,initial_bond_set_amount_lowest_seen,initial_bond_set_date_earliest_seen,bond_posted_amount_lowest_seen,bond_posted_date_earliest_seen,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
0,33342b2832acf82179e0df53a43d957099d262e4_2004-...,2,JCRLYTX; JCRLYTX,NaN,None,NaN,NaT,2004-12-05 22:30:00+00:00,2025-01-23 22:30:00+00:00,2025-01-23,...,2025-01-23 22:30:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Conroe,TX,Montgomery
1,de10c6a3d0027b9a7bf15e7ae0726e67f733bd81_2011-...,4,YORCOPA; MIAHOLD; FLDSSFS; KRO,1500.0,2020-10-26,1500.0,2011-02-18 00:00:00+00:00,2011-01-11 23:59:00+00:00,NaT,None,...,NaT,York,PA,York,York,PA,York,Miami,FL,Miami-Dade
2,ad00adabb36933a9ae532721b36b572b7a70b09f_2011-...,2,ECC; PIC,NaN,None,NaN,NaT,2011-05-11 13:00:35+00:00,2026-02-10 02:58:00+00:00,2026-02-10,...,2026-02-10 02:58:00+00:00,El Centro,CA,Imperial,El Centro,CA,Imperial,Los Fresnos,TX,Cameron
3,20acf28b12065c2144c5106fab1698f79c43a7a2_2012-...,3,HOUHOLD; MTGHOLD; MTGPCTX,NaN,None,NaN,NaT,2012-11-06 09:43:00+00:00,2026-01-27 12:00:00+00:00,2026-01-27,...,2026-01-27 12:00:00+00:00,Houston,TX,Harris,Houston,TX,Harris,Conroe,TX,Montgomery
4,367c0c726a1428444b6aefdbd0f6a2b877ad0f2f_2014-...,2,FREHOLD; LOSHOLD,NaN,None,NaN,NaT,2014-01-17 13:18:00+00:00,2025-02-08 05:28:00+00:00,2025-02-08,...,2025-02-08 05:28:00+00:00,None,CA,None,None,CA,None,Los Angeles,CA,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087412,6cece9f08499216f65ba3be7200e5bdb6b7add7e_2026-...,1,SJS,NaN,None,NaN,NaT,2026-03-10 23:40:00+00:00,NaT,None,...,NaT,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo,Guaynabo,PR,Guaynabo
1087413,a9792bfd2c9dc036a74e802047f3f9ee958892c1_2026-...,1,DHDFNJ,NaN,None,NaN,NaT,2026-03-10 23:47:00+00:00,NaT,None,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087414,1dd7bb2de9c3e8fc58962a25db518715b3cef54e_2026-...,1,DHDFNJ,NaN,None,NaN,NaT,2026-03-10 23:57:00+00:00,NaT,None,...,NaT,Newark,NJ,Essex,Newark,NJ,Essex,Newark,NJ,Essex
1087415,011a0c9d77115c9902c6b4f20667f2e2b75c85cb_2026-...,1,PLYMOMA,12000.0,None,1500.0,2012-05-18 00:00:00+00:00,2026-03-11 00:13:00+00:00,NaT,None,...,NaT,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth,Plymouth,MA,Plymouth
1087416,5a72db4bb17f84699ff794292f9dd0f5d86f12d9_2026-...,1,ELZICDF,NaN,None,NaN,NaT,2026-03-11 00:30:00+00:00,NaT,None,...,NaT,Elizabeth,NJ,Union,Elizabeth,NJ,Union,Elizabeth,NJ,Union

In [7]:
from datetime import datetime

In [8]:
##turning stay in book time to datetime so we can filter an do equations to it
df["stay_book_in_date_time"] = pd.to_datetime(df["stay_book_in_date_time"])

In [9]:
##whittling it to just 2025. this works because, factually, if someone was arrested in 2024, their detention stays
##following that arrest is not really going to be before the date. arrests LEAD to detentions

dfDetentions = df.loc[
  (df["stay_book_in_date_time"] >= "2024-01-01") &
  (df["stay_book_in_date_time"] <= "2024-12-31")]

In [10]:
dfDetentions

,stay_ID,n_stints,detention_facility_codes_all,initial_bond_set_amount_lowest_seen,initial_bond_set_date_earliest_seen,bond_posted_amount_lowest_seen,bond_posted_date_earliest_seen,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
357818,1d20c3a42b8bd7480ce1130ed1064fd9d52879c8_2024-...,1,ELZICDF,NaN,None,NaN,NaT,2024-01-01 00:04:00+00:00,2024-03-12 09:04:00+00:00,2024-03-12,...,2024-03-12 09:04:00+00:00,Elizabeth,NJ,Union,Elizabeth,NJ,Union,Elizabeth,NJ,Union
357819,075e4207b7d43315463e23a86f6ac6e3721b00d9_2024-...,2,CSCNWWA; CSCNWWA,15000.0,None,15000.0,2024-04-19 15:09:00+00:00,2024-01-01 02:01:00+00:00,2024-04-19 15:26:00+00:00,2024-04-19,...,2024-04-19 15:26:00+00:00,Tacoma,WA,Pierce,Tacoma,WA,Pierce,Tacoma,WA,Pierce
357820,18b01882ccc6997c2e36c61d42e2bea1bfe878e2_2024-...,1,CSCNWWA,NaN,None,NaN,NaT,2024-01-01 02:01:00+00:00,2024-01-23 16:00:00+00:00,2024-01-23,...,2024-01-23 14:01:00+00:00,Tacoma,WA,Pierce,Tacoma,WA,Pierce,Tacoma,WA,Pierce
357821,3a35b6f2c29cc5095b00a045cd8cfe0c9d1fa057_2024-...,1,CSCNWWA,NaN,None,NaN,NaT,2024-01-01 02:01:00+00:00,2024-01-23 16:00:00+00:00,2024-01-23,...,2024-01-23 14:01:00+00:00,Tacoma,WA,Pierce,Tacoma,WA,Pierce,Tacoma,WA,Pierce
357822,4dd2f6a12bc87e5527aaf8cf6a68b32067d74d60_2024-...,1,CSCNWWA,NaN,None,NaN,NaT,2024-01-01 02:01:00+00:00,2024-03-05 16:47:00+00:00,2024-03-05,...,2024-03-05 16:47:00+00:00,Tacoma,WA,Pierce,Tacoma,WA,Pierce,Tacoma,WA,Pierce
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636723,80faf97e6a7dc699f2dbd93890e74f851bdc29ea_2024-...,2,BALHOLD; MSVPCPA,NaN,None,NaN,NaT,2024-12-30 22:52:00+00:00,2025-03-20 19:28:00+00:00,2025-03-20,...,2025-03-20 19:28:00+00:00,Baltimore,MD,Baltimore,Philipsburg,PA,Clearfield,Philipsburg,PA,Clearfield
636724,0fa1ffba54ffe24120d6a137ca1217a700014a64_2024-...,3,ELZICDF; PINEPLA; JENATLA,NaN,None,NaN,NaT,2024-12-30 23:00:00+00:00,2025-02-03 19:00:00+00:00,2025-02-03,...,2025-02-03 19:00:00+00:00,Elizabeth,NJ,Union,Elizabeth,NJ,Union,Alexandria,LA,Rapides
636725,bfad84bcb0b54dbaefc9bb37aaa28aaef826e4ce_2024-...,2,DENICDF; WEBDCTX,NaN,None,NaN,NaT,2024-12-30 23:02:00+00:00,2025-03-27 04:00:00+00:00,2025-03-27,...,2025-03-27 04:00:00+00:00,Aurora,CO,Adams,Aurora,CO,Adams,Laredo,TX,Webb
636726,dfcd6c082a44dfe7952cf2b5a4827e40756b187a_2024-...,3,MTGPCTX; MTGPCTX; POLKCTX,5000.0,None,5000.0,2020-05-20 00:00:00+00:00,2024-12-30 23:29:00+00:00,2025-03-13 14:30:00+00:00,2025-03-13,...,2025-03-13 14:30:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Livingston,TX,Polk
636727,343faee3db9f7ea3f57cb664d2b5ed55a6225503_2024-...,2,MTGPCTX; MTGPCTX,NaN,None,NaN,NaT,2024-12-30 23:45:00+00:00,2025-01-02 17:30:00+00:00,2025-01-02,...,2025-01-02 17:30:00+00:00,Conroe,TX,Montgomery,Conroe,TX,Montgomery,Conroe,TX,Montgomery

In [12]:
##bringing in the unique identifiers from the arrests list so we can use that as a way to whittle this listfurther
dfArrestIDs = pd.read_csv(r"C:\Users\sshrestha\Desktop\Writing\DataProjects\ICE Deportations and Arrests\2024 Data\FilteredData\IDsNY2024Arrests_072226.csv")
dfArrestIDs

                             unique_identifier
0     0009f9ba7cc635f7620fd6d2b0be86f968c04d71
1     000e00362a7ce05a098386f88e81e146cef564b8
2     00119da62775f775fc6b28dbb06716f7306d6060
3     00143e74440995cd4e3e78c3db761ed59cd82db5
4     0026771284ae9e758f97c7b8b95ad0032990f3bb
...                                        ...
4107  ffeb4fd4dff55ed3b996bd1e935f7a443be1fe22
4108  fff8f3ae1841b2023ed0a646483fb585dcc7360a
4109  fffa9541d55830bab785c5a5b78cacf6fda28cfe
4110  fffc1c12e37bccf2693b5deb67a7f40b3744b156
4111  fffd8cddaedf2db4e037b8421d8bf22ae75a15fd

[4112 rows x 1 columns]

In [13]:
##now wwe ask the notebook to use these unique identifiers to pull only those from the detentions list
filtered_detentions = dfDetentions[dfDetentions['unique_identifier'].isin(dfArrestIDs['unique_identifier'])]
filtered_detentions

,stay_ID,n_stints,detention_facility_codes_all,initial_bond_set_amount_lowest_seen,initial_bond_set_date_earliest_seen,bond_posted_amount_lowest_seen,bond_posted_date_earliest_seen,stay_book_in_date_time,stay_book_out_date_time,stay_book_out_date,...,book_out_date_time_last,city_first,state_first,county_first,city_longest,state_longest,county_longest,city_last,state_last,county_last
358204,3a20b7a9430ef9bec2aef8012f6d91aad6ed37a6_2024-...,1,NYCHOLD,NaN,None,NaN,NaT,2024-01-02 11:00:00+00:00,2024-01-02 14:00:00+00:00,2024-01-02,...,2024-01-02 14:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
358207,ce2794a47d606e463f4ddd95f666ac779e90ed2c_2024-...,1,NYCHOLD,NaN,None,NaN,NaT,2024-01-02 11:00:00+00:00,2024-01-02 14:00:00+00:00,2024-01-02,...,2024-01-02 14:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
358225,888de310fe038e5b89ed1632f20419871160656e_2024-...,1,NYCHOLD,NaN,None,NaN,NaT,2024-01-02 11:40:00+00:00,2024-01-02 13:57:00+00:00,2024-01-02,...,2024-01-02 13:57:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
358229,6b008436ccb67f2ac8d6b05ee20699e4049ecf27_2024-...,1,NYCHOLD,NaN,None,NaN,NaT,2024-01-02 11:50:00+00:00,2024-01-02 14:00:00+00:00,2024-01-02,...,2024-01-02 14:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
358241,8f53fae86d9922ca9ecd135a04c8edb6cfe8cc30_2024-...,1,NYCHOLD,NaN,None,NaN,NaT,2024-01-02 11:56:00+00:00,2024-01-02 14:00:00+00:00,2024-01-02,...,2024-01-02 14:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635893,444fa4416359287dcf417fb40faebf4a4c923061_2024-...,1,NYCHOLD,NaN,None,NaN,NaT,2024-12-30 09:00:00+00:00,2024-12-30 12:16:00+00:00,2024-12-30,...,2024-12-30 12:16:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
635898,9fb37017353ed90f73d5ad53fe3746d4003b8c8b_2024-...,1,NYCHOLD,NaN,None,NaN,NaT,2024-12-30 09:00:00+00:00,2024-12-30 13:00:00+00:00,2024-12-30,...,2024-12-30 13:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
635900,a57304e18c231e2affb9fd20d94043f04b5ce857_2024-...,1,NYCHOLD,NaN,None,NaN,NaT,2024-12-30 09:00:00+00:00,2024-12-30 13:00:00+00:00,2024-12-30,...,2024-12-30 13:00:00+00:00,New York,NY,New York,New York,NY,New York,New York,NY,New York
635931,f999e21c601a364dfe6e62e9b2dc565603b31652_2024-...,3,BTV; PINEPLA; JENATLA,NaN,None,NaN,NaT,2024-12-30 09:55:00+00:00,2025-01-30 07:13:00+00:00,2025-01-30,...,2025-01-30 07:13:00+00:00,Batavia,NY,Genesee,Batavia,NY,Genesee,Alexandria,LA,Rapides
636022,aacb6302237500ad65662cec2822c457a9d115fc_2024-...,5,NYCHOLD; MSVPCPA; PIKCOPA; NYCHOLD; NASSANY,NaN,None,NaN,NaT,2024-12-30 10:49:00+00:00,2025-03-08 20:32:00+00:00,2025-03-08,...,2025-03-08 13:00:00+00:00,New York,NY,New York,Philipsburg,PA,Clearfield,East Meadow,NY,Nassau

In [14]:
filtered_detentions.to_csv('Filtereddata/2024DetentionsofNYArrests_072226.csv', index = False)

In [15]:
##preliminary analysis
appear = filtered_detentions['unique_identifier'].value_counts()
appear

unique_identifier
c49684bdf6b6f3b1110627341b5db57df7aff218    4
6217b8f0bc57e66a07b36dc92f3a948d8035c7ce    3
06be6ebf6cb31f2df052d68cca6e46e258194406    2
8f3d67781823da48df19fa928007437a28df9de3    2
911a0da94085e76005801951b55bafbd95bf5ec2    2
                                           ..
3c8471a9e31e35435910e31b59cc4988e5fc8b24    1
a1520a7bf22278aa207171d8915a39707b6728ab    1
98af6b53571bfc098eb961b96c8bfe462690a4f4    1
0699559910ff416180f621d832a28bcd3e429e90    1
aacb6302237500ad65662cec2822c457a9d115fc    1
Name: count, Length: 3594, dtype: int64